export const FILLER_WORDS = [
"MĀJA","LAIKS","SAULE","MĀTE","TĒVS","BĒRNS","ŪDENS","MAIZE","GAISS","ZEME","NAKTS","DIENA","MEŽS","CEĻŠ","LIETUS","SNIEGS","VĒJŠ","UGUNS","ZĀLE","PUTNS","ZIVS","ZIRGS","GOVS","KAĶIS","SUNS","BITE","LAPA","KOKS","ROKAS","KĀJAS","GALVA","SIRDS","ACIS","MUTE","AUSIS","MATI","ISTABA","LOGS","DURVIS","JUMTS","GALDS","KRĒSLS","GULTA","PIENS","SIERS","GAĻA","ĀBOLS","MEDUS","RUDENS","VASARA","ZIEMA","RĪTS","VAKARS","GADS","STUNDA","SKOLA","PILSĒTA","CIEMS","EZERS","UPE","KALNS","PĻAVA","JŪRA","DRAUGS","SIEVA","VĪRS","MĀSA","BRĀLIS","DARBS","NAUDA","LAIME","MIERS","PRIEKS"
];

export const FALLBACK_LEVELS = {
1:[{q:"Sarkans gailis zemē dzied.",a:"Burkāns"},{q:"Akmeņa kājas, koka rumpis, salmu cepure.",a:"Māja"},{q:"Kas stāv pie griestiem ar kājām uz augšu?",a:"Muša"},{q:"Mežā dzimis, mežā audzis, atnāk mājā par saimnieku būt.",a:"Galds"},{q:"Balta zeme, melna sēkla.",a:"Grāmata"},{q:"Maza muciņa divejāds alutiņš.",a:"Ola"},{q:"Kas taisa tiltu bez neviena baļķa.",a:"Sals"},{q:"Četri taisa vietu, divi rāda uguni, viens pats apgulstas.",a:"Suns"},{q:"Apaļš kā rullis, sarkans kā bullis, šķēres padusē.",a:"Vēzis"},{q:"Mēness skala galā.",a:"Svece"}],
2:[{q:"Sarkans vīriņš, zaļa bārdiņa.",a:"Burkāns"},{q:"Mazs, mazs sunītis simts adatu mugurā.",a:"Ezis"},{q:"Bez rokām, bez cirvja uztaisa mājiņu.",a:"Skudra"},{q:"Krustiem šķērsiem kauli likti, pati miesa cauri spīd.",a:"Logs"},{q:"Kas dara raudas bez gaudām?",a:"Sīpols"},{q:"Cērt ledu, uzcērt sudrabu, cērt sudrabu, uzcērt zeltu.",a:"Ola"},{q:"Aka bez dibena.",a:"Gredzens"},{q:"Stabiņš sūnās, galdiņš virsū.",a:"Sēne"},{q:"Maza, maza mājiņa, ne tai logu, ne durvju.",a:"Ola"},{q:"Melns pirtī ienāk, sarkans iznāk.",a:"Vēzis"}],
3:[{q:"Mazs, mazs vīriņš, ass, ass cirvīts.",a:"Bite"},{q:"Lec kā zaķis, nav zaķis. Peld kā zivs, nav zivs.",a:"Varde"},{q:"Kas ziemu nesalst un vasaru neizkūst.",a:"Akmens"},{q:"Ik rītus viešiņa pa istabu skrien.",a:"Izkapts"},{q:"Pieci kambari, vienas durvis.",a:"Cimds"},{q:"Mazs, mazs vīriņš līkām kājām zaļi svārki mugurā.",a:"Sienāzis"},{q:"Dzelža cūciņa, pakala astīte.",a:"Adata"},{q:"Mežs kalnā. Es lejā. Es par mežu lielāks.",a:"Kāposti un vagas"},{q:"Papriekš sarkans un tad melns.",a:"Ogle"},{q:"Divi mazi zirnīši apsēj visu pasauli.",a:"Acis"}],
4:[{q:"Pelēka aitiņa – astīte sānos.",a:"Cimds"},{q:"Caurums pie cauruma, bet tomēr stipris.",a:"Ķēde"},{q:"Maza, maza mājiņa stāv uz tievas kājiņas. Simtu kambaru, katrā kambarī pa simts mamzelīšu.",a:"Magone"},{q:"Mazs, mazs vīriņš, deviņas ādiņas. Kas tās dīrās, tas gauži raudās.",a:"Sīpols"},{q:"Galds runā – saime klusē.",a:"Cūka ar sivēniem"},{q:"Pieci baļķi māju taisa visi pieci atliekās.",a:"Audekls"},{q:"Pilna kūtiņa sarkanu aitiņu, ieiet garais izvajā!",a:"Krāsns"},{q:"Maza, maza muciņa, melns alutiņš.",a:"Tintnīca"},{q:"Ne čiku, ne grabu, labrīt pie loga.",a:"Gaisma"},{q:"Kas iet uz galvas baznīcā?",a:"Kāja zābakā"}],
5:[{q:"Div pilnas laktiņas baltu vistiņu.",a:"Zobi un mēle"},{q:"Divas ielas bērza malkas, vidū elkšņa pagale.",a:"Zobi un mēle"},{q:"Mazs, mazs zirdziņš, dienu nakti jājams.",a:"Slieksnis"},{q:"Sarkans suns lēkā aiz kaula sētiņas.",a:"Mēle"},{q:"Pakulu ķēve – linu aste.",a:"Adata un diegs"},{q:"Ozola dēlīts purviņā mirkst.",a:"Mute un mēle"},{q:"Pīpīts lēca, pīpīts deja, pīpa pēdu nepazina.",a:"Šūpulis"},{q:"Maza, maza sieviņa franciski runā.",a:"Bezdelīga"},{q:"Stabiņš sūnās, galdiņš virsū.",a:"Sēne"},{q:"Vīrs sēd uz jumta un pīpē.",a:"Skurstenis"}],
6:[{q:"Divas māsiņas viena vienā ceļa malā, otra otrā. Viena otru neredz.",a:"Acis"},{q:"Pēdu garš, tomēr pēda nav.",a:"Kurpe"},{q:"Četri brāļi iet pa ceļu, visiem bārdas atpakaļ.",a:"Zirga kājas"},{q:"Četri mācītāji zem vienas cepures.",a:"Galda kājas"},{q:"Pa dienu apkārt staigā, pa nakti karājas.",a:"Pastalas"},{q:"Mūsu pašu lielam kungam lūku ritens uz pakaļas.",a:"Suns ar asti"},{q:"Sarkana cūciņa astru astīte.",a:"Dzērvene sūnās"},{q:"Plikais līkais karājās, spalvainais lūrējās.",a:"Kaķis un desa"},{q:"Papriekš bērni dzimst, tad tik māte.",a:"Siens un siena guba"},{q:"Maza, maza sieviņa simtu miču galvā.",a:"Kāpostgalva"}],
7:[{q:"Ar kājām min, ar vēderu trin – papleš un iebāž.",a:"Auž"},{q:"Mežā dzimis, mežā audzis – pārnāk mājās – cilā asti.",a:"Akas vinda"},{q:"Mežā dzimis, mežā audzis, pārnāk mājās, gauži raud.",a:"Vijole"},{q:"Nasta pūš – nesējs nē.",a:"Jātnieks un zirgs"},{q:"Vīrs niķu niķiem svārks stiķu stiķiem; kaula seja, gaļas bārda.",a:"Gailis"},{q:"Tālāk nosviežu kā noeju.",a:"Prāts"},{q:"Divi dur, divi vēzās.",a:"Maizi mīca"},{q:"Sarkana telīte astē piesieta.",a:"Ķirsis"},{q:"Līdaka aizskrēja, līdaka atskrēja. Daugava sasala trinkšķēdama.",a:"Audekls"},{q:"Vienā galā tā kā kārts, otrā galā tā kā ķeksis, vidū kā kumoss, danco kā jaunava.",a:"Žagata"}],
8:[{q:"Divi rulles, divi tulles, četri zemes mērītāji, devīts kaŗa vajātājs.",a:"Govs"},{q:"Jo cūciņa skrien, jo barojas.",a:"Ratiņa spole"},{q:"Melns dejo, melns lec, pēdas vien nepaliek.",a:"Blusa kož cilvēkam"},{q:"Sešders siekstu kustināja.",a:"Blusa kož cilvēkam"},{q:"Simtacs gāja viesus lūgt.",a:"Tīkls"},{q:"Zila govs zemi laiza.",a:"Izkapts"},{q:"Ielāps uz ielāpa nav ielāp, zied kā puķe nav puķe.",a:"Kāpostgalva"},{q:"Šmurgulīts ar vienu ausi.",a:"Ķipītis"},{q:"Avens vērša vēderā.",a:"Zeķe zābakā"},{q:"Tieva, gaŗa jumprava – utu pilna galva.",a:"Kaņepe"}],
9:[{q:"Kad es biju maziņa, man bij balta kleitiņa. Nu es esmu liela – mana sirds ir tik cieta kā akmens.",a:"Ķirsis"},{q:"Kāpi, puisīti, man virsū, krati, grūsti – tev būs labums, man būs vieglums.",a:"Ābele"},{q:"Ej tu pa vienu pusi, es iešu pa otru pusi, un uz putras kalna satiksimies.",a:"Josta ap vidukli"},{q:"Tēvs vēl nav dzimis, jau dēls skursteņa galā.",a:"Uguns un dūmi"},{q:"Vēl zirgs nav sajūgts, jau stāvus.",a:"Dūmi un uguns"},{q:"Velns iet pa riju, boms mugurā.",a:"Kaķis"},{q:"Tieva gaŗa freilenīte – tālu spļauj.",a:"Šautene"},{q:"Pārcērt ledu, atrod sudrabu. Pārcērt sudrabu, atrod zeltu.",a:"Ola"},{q:"Balta, balta baznīciņa, ne logi, ne durvis. Ubags vidū dzied.",a:"Cālis olā"},{q:"Teļš bez mēles kalnu starpā bļauj.",a:"Pirdiens"}],
10:[{q:"Viņa viņu mīl, viņš viņu nemīl. Ja viņa viņu atrod, tad viņa ir laimīga, bet ja viņš viņu atrod, tad viņai ir nāve.",a:"Suns un blusa"},{q:"Viņā zemē zirgu jūdzu, šai zemē loks atsprāga.",a:"Varavīksne"},{q:"Vīrs brauc pa mežu – zarnas klēpī.",a:"Braucējs un groži"},{q:"Arājs ar tīrumā samta svārki mugurā.",a:"Kurmis"},{q:"Cik vajag naglu labi apkaltam zirgam?",a:"Nevienas"},{q:"Kur gailis lec, kad gadu vecs?",a:"Otrā gadā"},{q:"Kurā krūzē nevar ieliet ūdeni?",a:"Pilnā"},{q:"Kas tas par suni, kas tikai septītā dienā rej.",a:"Mācītājs"},{q:"Jo atņem – top lielāks, liek klāt – mazāks.",a:"Bedre"},{q:"Mežā dzimis, mežā audzis, pārnāk mājās, gauži raud.",a:"Vijole"}],
};

export const FALLBACK_BONUS = 
[{q:"Tieva mana kājiņa, maza mana galviņa, bet kad meitas ģērbties sāk, bez manis maz ko darīt māk.",a:"Kniepadata"},{q:"Pelēks auns cauru muguru apēd visu vasaras krājumu.",a:"Dzirnavas"},{q:"Ne ugunī deg, ne ūdenī slīkst.",a:"Ēna"}];
